# -*- coding: utf-8 -*-
"""Examen Visualización de Datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1clcKFxiS2l0wZclvh9rcg4AuyigzmYh0
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df_summer = pd.read_csv('/content/drive/MyDrive/Work 2/5to Semestre/Visualización de Datos/summer2016.csv')
df_summer.head()

df_summer = df_summer.assign(
    BMI = df_summer['Weight'] / (df_summer['Height'] / 100)**2
)
df_summer.head()

deportes = ['Swimming', 'Judo']
atletas_filtrados = df_summer.query(
    "(Sport in @deportes) & (Age > 30)"
)
atletas_filtrados.head()

stats_equipo = df_summer.groupby('Team').agg({
    'Age': 'mean',
    'Height': 'max'
})
stats_equipo.head()

nombres_oro = df_summer.loc[df_summer['Medal'] == 'Gold', 'Name']
nombres_oro.head()

df_ordenado = df_summer.sort_values(
    by=['Sport', 'Age'],
    ascending=[True, False]
)
df_ordenado.head()

