# -*- coding: utf-8 -*-
"""Using libraries in Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZZUzt7ml1GN7yj5CO7mWnsutKkbZu4y
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

penguins_data = pd.read_csv('https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins.csv')

(penguins_data
 .filter(['species', 'island', 'sex'], axis = 1)
).head()

#Convertir variables categóricas al tipo categoría
penguins_data[['species', 'island', 'sex']] = (penguins_data.
                                               filter(['species', 'island', 'sex'], axis = 1).
                                               astype('category'))
'''
 o este también es viable
 penguins_data[['species', 'island', 'sex']] = penguins_data[['species', 'island', 'sex']].astype('category')
'''

(penguins_data
 .filter(['species', 'island', 'sex'], axis = 1)
 .info()
 )

(penguins_data
 .filter(['species'], axis = 1)
 .value_counts()
 )

#otro método más facil (que el profe no enseña)
# penguins_data['species'].value_counts()

# Para encontrar la frecuencia relativa, o sea el porcentaje (%) de la cuenta de especies en relación con la cuenta total
(penguins_data
 .filter(['species'], axis = 1)
 .value_counts(normalize = True)
 )

# Gráficos de barras
plt.figure(figsize = (8, 6))
sns.countplot(data = penguins_data, x = 'species')
plt.title('Número de especies de pingüinos')
plt.show()

#Gráfico de frecuencias relativas
penguin_counts = penguins_data['species'].value_counts(normalize = True)
plt.figure(figsize = (6, 4))
sns.barplot(x = penguin_counts.index, y = penguin_counts.values, color='skyblue')
plt.title('Distribución de especies de pingüinos')
plt.xlabel('Especie')
plt.ylabel('Frecuencia relativa')
plt.show()

# Gráfico circular o pie
plt.figure(figsize = (6, 6))
plt.pie(penguin_counts.values, labels = penguin_counts.index, autopct = '%1.1f%%', startangle = 90, colors = ['lightcoral', 'gold', 'lightgreen'])
plt.title('Proporcion de pinguinos')
plt.show()

## Otra manera ##
penguin_counts = penguins_data['species'].value_counts()
plt.figure(figsize = (6, 6))
plt.pie(penguin_counts.values, labels = penguin_counts.index, autopct = '%1.1f%%', startangle = 90)
plt.title('Distribución de especies de pingüinos')
plt.show()

