---
title: "Lists"
author: "Sebastián Quevedo - A01722937"
date: "2024-05-20"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Test 1
```{r}
x = c(1, 2, 5, 6, 8)
y = c(x[1:3], 7, 9)
xy = x + y
x
y
xy

num_list <- list(1,2,3,4,5)
day_list <- list("Mon","Tue","Wed", "Thurs", "Fri")
merge_list <- c(num_list, day_list)
merge_list

#Create lists.
int_list <- list(1:5)
print(int_list)
int_list2 <- list(10:14)
print(int_list2)

#Convert the lists to vectors.
vec1 <- unlist(int_list)
vec2 <- unlist(int_list2)
print(vec1)
print(vec2)

#Now add the vectors.
sum <- vec1 + vec2 
print(sum)
```

# Test 2
```{r}
data_list <- list(c("Jan","Feb","Mar"), matrix(c(1,2,3,4,-1,9), nrow = 2),list("Red",12.3))
names(data_list) <- c("Monat", "Matrix", "Misc")
print(data_list)

-5:5

c(1, 2, 3) + 4

#Predefined Lists
letters
LETTERS
month.abb
month.name

#c function in R
#The c function in R combines the parameter into a list and converts them to the same type.
c("April", 4)
typeof("4")

vec <- c(1:4)
str <- c('Joy', 'Peace', 'Long-suffering', 'Love')
make_list <- list(vec, str)
names(make_list) <- c('vector', 'string')
make_list[[2]] <- c('God', 'Jesus', 'Holy Spirit', 'Love')
make_list
```






